agenda/agenda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

agenda/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

    
urlpatterns = [
    path('', views.render_main, name='home'),
    path('salvar/', views.save_cadastro, name='save_cadastro'),
    path('pesquisa/', views.listar_cadastro, name='list_cadastro'),
    path('listar/', views.edit_cadastro, name='edit_cadastro'),
    path('excluir-cadastro/', views.excluir_cadastro, name='delete_cadastro'),

]

agenda/main/models.py
from django.db import models
from django.utils import timezone

class Cadastro(models.Model):
    Id = models.AutoField(primary_key=True)
    data_criacao = models.DateTimeField(default=timezone.now)  
    nome = models.CharField(max_length=100, null=True)
    cnpj = models.CharField(max_length=14, null=True)
    cpf = models.CharField(max_length=14, null=True)
    ie = models.CharField(max_length=20, null=True)
    cidade = models.CharField(max_length=100, null=True)
    bairro = models.CharField(max_length=100, null=True)
    endereco = models.CharField(max_length=100, null=True)
    cep = models.CharField(max_length= 100, null=True)
    telefone = models.CharField(max_length=15, null=True) 
    whatsapp = models.CharField(max_length=15, null=True)
    email = models.EmailField()
    celular = models.CharField(max_length=15, null=True)
    def __str__(self):
        return self.nome

class Observacoes(models.Model):
    cadastro = models.ForeignKey(Cadastro, on_delete=models.CASCADE)
    observacoes = models.CharField(max_length=100, null=True)
    def __str__(self):
        return self.observacoes

agenda/main/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from .models import Cadastro, Observacoes

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q


def render_main(request):

    return render(request, 'screens/main.html')

def edit_cadastro(request):
    if request.method == 'POST':
        edit_id = request.POST.get('editId')

        edit_cpf = request.POST.get('editCPF')
        edit_cnpj = request.POST.get('editCNPJ')

        if len(edit_cnpj) == 14:
            cnpj = '{}.{}.{}/{}-{}'.format(edit_cnpj[:2], edit_cnpj[2:5], edit_cnpj[5:8], edit_cnpj[8:12], edit_cnpj[12:])
        else:
            cnpj = edit_cnpj if edit_cnpj else ''

        if len(edit_cpf) == 11:
            cpf = '{}.{}.{}-{}'.format(edit_cpf[:3], edit_cpf[3:6], edit_cpf[6:9], edit_cpf[9:11])
        else:
            cpf = edit_cpf if edit_cpf else ''


        cadastro = get_object_or_404(Cadastro, pk=edit_id)
        cadastro.nome = request.POST.get('editNome')
        cadastro.cpf = cpf
        cadastro.cnpj = cnpj
        cadastro.ie = request.POST.get('editIE')
        cadastro.endereco = request.POST.get('editEndereco')
        cadastro.cidade = request.POST.get('editCidade')
        cadastro.bairro = request.POST.get('editBairro')
        cadastro.cep = request.POST.get('editCEP')
        cadastro.telefone = request.POST.get('editTelefone')
        cadastro.celular = request.POST.get('editCelular')
        cadastro.whatsapp = request.POST.get('editWhatsapp')
        cadastro.email = request.POST.get('editEmail')
        cadastro.save()


        # Editar observações
        edit_observacoes = request.POST.get('editObservacoes')
        observacoes = Observacoes.objects.filter(cadastro=cadastro)
        if observacoes.exists():
            observacao = observacoes.first()
            observacao.observacoes = edit_observacoes
            observacao.save()
        else:
            nova_observacao = Observacoes(cadastro=cadastro, observacoes=edit_observacoes)
            nova_observacao.save()

        return HttpResponseRedirect('/pesquisa/')



def save_cadastro(request):
    if request.method == 'POST':
        nome_fornecedor = request.POST.get('nome')
        endereco = request.POST.get('endereco')
        cidade = request.POST.get('cidade')
        bairro = request.POST.get('bairro')
        rua = request.POST.get('rua')
        cnpj = request.POST.get('cnpj')
        cpf = request.POST.get('cpf')
        cep = request.POST.get('cep')
        ie = request.POST.get('ie')
        telefone = request.POST.get('telefone')
        whatsapp = request.POST.get('whatsapp')
        email = request.POST.get('email')
        celular = request.POST.get('celular')
        observacoes = request.POST.get('observacoes')
        print(endereco)
        if cnpj != '':
            cnpj = '{}.{}.{}/{}-{}'.format(cnpj[:2], cnpj[2:5], cnpj[5:8], cnpj[8:12], cnpj[12:])
        else:
            cnpj = ''
        if cpf != '':
            cpf = '{}.{}.{}-{}'.format(cpf[:3], cpf[3:6], cpf[6:9], cpf[9:11])
        else: 
            cpf = ''
    
   
        novo_cadastro = Cadastro.objects.create(
            nome=nome_fornecedor,
            endereco=endereco,
            cidade=cidade,
            bairro=bairro,
            cnpj=cnpj,
            cpf=cpf,
            ie=ie,
            cep=cep,
            telefone=telefone,
            whatsapp=whatsapp,
            email=email,
            celular=celular
        )
        nova_observacao = Observacoes.objects.create(
            cadastro=novo_cadastro,
            observacoes=observacoes
        )
        nova_observacao.save()

        return HttpResponseRedirect('/')
    return HttpResponse('Erro ao criar novo registro de fornecedor e produto')

def listar_cadastro(request):
    query_observacoes = request.GET.get('q_observacoes')
    query_informacoes = request.GET.get('q_informacoes')

    all_cadastros = Cadastro.objects.all()

    filters = Q()

    if query_observacoes:
        filters |= Q(observacoes__observacoes__icontains=query_observacoes)

    if query_informacoes:
        filters |= (
            Q(nome__icontains=query_informacoes) |
            Q(cnpj__icontains=query_informacoes) |
            Q(cpf__icontains=query_informacoes) |
            Q(ie__icontains=query_informacoes)
        )

    if filters:
        all_cadastros = all_cadastros.filter(filters).distinct()

    all_cadastros = all_cadastros.order_by('-data_criacao')

    cadastros_por_pagina = 10
    paginator = Paginator(all_cadastros, cadastros_por_pagina)
    
    page_number = request.GET.get('page')
    try:
        cadastros = paginator.page(page_number)
    except PageNotAnInteger:
        cadastros = paginator.page(1)
    except EmptyPage:
        cadastros = paginator.page(paginator.num_pages)

    context = {'cadastros': cadastros}
    return render(request, 'screens/lista.html', context)


def excluir_cadastro(request):
    if request.method == 'POST':
        cadastro_id = request.POST.get('cadastro_id')
        try:
            cadastro = Cadastro.objects.get(pk=cadastro_id)
            cadastro.delete()
            return HttpResponseRedirect('/pesquisa/')
        except Cadastro.DoesNotExist:
            return JsonResponse({'error': 'Cadastro não encontrado'}, status=404)

agenda/main/templates/components/criar_cadastro.html
{% load static %}
<style>
  .btn {
    padding: 10px 20px;
    border-radius: 8px;
    background-color: #f0f0f0;
    color: #333;
    text-decoration: none;
    box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.2), -4px -4px 10px rgba(255, 255, 255, 0.9);
    transition: all 0.3s ease;
    display: inline-block;
    cursor: pointer;
    border: none;
    outline: none;
  }

  .btn:hover {
    background-color: #e0e0e0;
    box-shadow: 6px 6px 15px rgba(0, 0, 0, 0.3), -6px -6px 15px rgba(255, 255, 255, 0.9);
    transform: translateY(-2px);
  }

  .form-control {
    width: 100%;
    padding: 10px;
    border-radius: 8px;
    border: none;
    background-color: #f0f0f0;
    box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.2), -4px -4px 10px rgba(255, 255, 255, 0.9);
  }

  .form-control:focus {
    outline: none;
    /* Removendo a borda de foco padrão */
    box-shadow: 6px 6px 15px rgba(0, 0, 0, 0.3), -6px -6px 15px rgba(255, 255, 255, 0.9);
    /* Estilo enquanto o input está em foco */
  }

  .btn-danger {
    padding: 5px 10px;
    border-radius: 50%;
    background-color: #f0f0f0;
    color: #333;
    text-decoration: none;
    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2), -2px -2px 5px rgba(255, 255, 255, 0.9);
    transition: all 0.3s ease;
    border: none;
    outline: none;
  }

  .btn-danger:hover {
    background-color: #e0e0e0;
    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.4), -3px -3px 8px rgba(255, 255, 255, 0.9);
    transform: scale(1.1) rotate(5deg);
  }

  .neuromorphic-input {
    border: none;
    border-radius: 8px;
    margin-right: 8px;
    background-color: #f0f0f0;
    padding: 10px;
    font-size: 13px;
    box-shadow: 5px 5px 15px #bebebe,
      -5px -5px 15px #ffffff;
    transition: transform 0.3s ease-in-out;

    width: 300px;
  }

  .neuromorphic-input:focus {
    outline: none;
  }

  .neuromorphic-input:hover {
    background-color: #e0e0e0;
    box-shadow: 6px 6px 15px rgba(0, 0, 0, 0.3), -6px -6px 15px rgba(255, 255, 255, 0.9);
    transform: translateY(-2px);
  }

  .neuromorphic-button {
    border: none;
    border-radius: 8px;
    background-color: #f0f0f0;
    padding: 10px 20px;
    box-shadow: 5px 5px 15px #bebebe,
      -5px -5px 15px #ffffff;
    cursor: pointer;
    font-size: 13px;
    transition: transform 0.3s ease-in-out;
    width: 100px;
  }

  .neuromorphic-button:hover {
    background-color: #e0e0e0;
    box-shadow: 6px 6px 15px rgba(0, 0, 0, 0.3), -6px -6px 15px rgba(255, 255, 255, 0.9);
    transform: translateY(-2px);
  }

  .form-label {
    font-size: 16px;
    font-weight: bold;
  }
</style>

<div class="container mt-5">
  <div style="display: flex; align-items: center; justify-content: space-between;">
    <h2 class="mb-4">Criar cadastro</h2>
    <form method="GET" action="{% url 'list_cadastro' %}" style="display: flex; align-items: center;">
      <input type="text" name="q_observacoes" placeholder="Pesquisar Observações" class="neuromorphic-input">
      <input type="text" name="q_informacoes" placeholder="Pesquisar Informações" class="neuromorphic-input">
      <button type="submit" class="neuromorphic-button">Pesquisar</button>
    </form>
  </div>
</div>

<form action="{% url 'save_cadastro' %}" method="post">
  {% csrf_token %}
  <div class="mb-3">
    <label for="nome" class="form-label">Nome:</label>
    <input type="text" class="form-control" placeholder="Nome" id="nome" name="nome">
  </div>
  <div class="mb-3">
    <label for="endereco" class="form-label">Endereço:</label>
    <input type="text" class="form-control" placeholder="Endereço" id="endereco" name="endereco">
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <label for="cidade" class="form-label">Cidade:</label>
      <input type="text" class="form-control" placeholder="Cidade" id="cidade" name="cidade">
    </div>
    <div class="col-md-6 mb-3">
      <label for="bairro" class="form-label">Bairro:</label>
      <input type="text" class="form-control" placeholder="Bairro" id="bairro" name="bairro">
    </div>
    <div class="col-md-6">
      <label for="cep" class="form-label">CEP:</label>
      <input type="text" class="form-control" placeholder="CEP" id="cep" name="cep">
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <label for="cpf" class="form-label">CPF:</label>
      <input type="text" class="form-control" placeholder="CPF" id="cpf" name="cpf">
    </div>
    <div class="col-md-6">
      <label for="cnpj" class="form-label">CNPJ:</label>
      <input type="text" class="form-control" placeholder="CNPJ" id="cnpj" name="cnpj">
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <label for="ie" class="form-label">IE:</label>
      <input type="text" class="form-control" placeholder="Inscrição Estadual" id="ie" name="ie">
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="row mb-3">
    <div class="col-md-6">
      <label for="telefone" class="form-label">Telefone:</label>
      <input type="text" class="form-control" placeholder="Telefone" id="telefone" name="telefone">
    </div>

    <div class="col-md-6">
      <label for="whatsapp" class="form-label">WhatsApp:</label>
      <input type="text" class="form-control" placeholder="WhatsApp" id="whatsapp" name="whatsapp">
    </div>
  </div>

  <div class="mb-3">
    <label for="celular" class="form-label">Celular:</label>
    <input type="text" class="form-control" placeholder="Celular" id="celular" name="celular">
  </div>

  <div class="mb-3">
    <label for="email" class="form-label">Email:</label>
    <input type="text" class="form-control" placeholder="Email" id="email" name="email">
  </div>

  <div class="mb-3">
    <label for="observacoes" class="form-label">Observações:</label>
    <input type="text" class="form-control" placeholder="Observações" id="observacoes" name="observacoes">
  </div>
  <button type="submit" class="btn">Salvar Dados</button>
</form>
</div>
<br>
<br>

agenda/main/templates/components/listar_cadastro.html
{% load static %}
<style>
.neuromorphic-card {
  background-color: #f4f4f4;
  border-radius: 10px;
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
  margin-bottom: 20px;
  border: none;
  width: 100%;
  
}
 
.card-title {
  font-size: 22px;
  font-weight: bolder;
  margin-bottom: 8px;
  text-transform: uppercase;
}

.info-label{
  font-size: 16px;
  font-weight: bold;
}

.info-value, .cadastro-list {
  font-size: 16px;
  margin-bottom: 5px;
}

.info-row{
  margin-bottom: 10px
}

.pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 20px;
}

.step-links {
  display: flex;
  justify-content: center;
  align-items: center;
}

.step-links a {
  text-decoration: none;
  padding: 15px 25px;
  border-radius: 12px;
  margin: 0 15px;
  background-color: #f0f0f0;
  color: #333;
  font-size: 13px; 
  box-shadow: 6px 6px 15px rgba(0, 0, 0, 0.3),
              -6px -6px 15px rgba(255, 255, 255, 0.9);
  transition: all 0.3s ease;
}

.step-links a:hover {
  background-color: #e0e0e0;
  box-shadow: 6px 6px 15px rgba(0, 0, 0, 0.3), -6px -6px 15px rgba(255, 255, 255, 0.9);
  transform: translateY(-2px);
}

.current {
  margin: 0 18px;
  font-weight: bold;
  font-size: 18px;
}

.btn-container {
  text-align: right;
  margin-bottom: 20px;
}

.btn-add {
  padding: 12px 20px;
  border-radius: 8px;
  background-color: #f0f0f0;
  color: #333;
  text-decoration: none;
  box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.2),
              -4px -4px 10px rgba(255, 255, 255, 0.9);
  transition: all 0.3s ease;
  display: inline-block;
}

.btn-add i {
  margin-right: 8px;
}

.btn-add:hover {
  background-color: #e0e0e0;
  box-shadow: 6px 6px 15px rgba(0, 0, 0, 0.3), -6px -6px 15px rgba(255, 255, 255, 0.9);
  transform: translateY(-2px);
}

.expand-toggle {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  margin-top: -30px;
  margin-right: 10px;
}

.icon-angle-down {
  font-size: 24px;
  cursor: pointer;
  transition: transform 0.3s;
  padding: 5px;
}

.icon-rotate {
  transform: rotate(180deg);
}

.fa-pen-to-square, .fa-trash{
  font-size: 20px;
  cursor: pointer;
  padding: 5px;
  margin-right: 8px;
}

.modal-backdrop {
   display: none;
}

.modal-content {
  background-color: #f4f4f4;
  border-radius: 10px;
  box-shadow: 0 4px 20px 0 rgba(0, 0, 0, 0.393), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
  border: none;
  font-size: 18px;
  font-weight: bold;
}

.modal-dialog {
  max-width: 90%; 
  margin: 1.75rem auto;

}

.modal-header {
  background-color: #f4f4f4;
  border-bottom: none;
  border-radius: 10px 10px 0 0;
}

.modal-title {
  font-size: 22px;
  font-weight: bold;
  color: #333;
}

.modal-body {
  padding: 20px;

}

.btn-primary {
  border-radius: 8px;
  background-color: #f0f0f0;
  color: #333;
  box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.2), -4px -4px 10px rgba(255, 255, 255, 0.9);
  transition: all 0.3s ease;
}

.btn-primary:hover {
  background-color: #e0e0e0;
  box-shadow: 6px 6px 15px rgba(0, 0, 0, 0.3), -6px -6px 15px rgba(255, 255, 255, 0.9);
  transform: translateY(-2px);
}

.form-control {
  width: 100%;
  padding: 10px;
  border-radius: 8px;
  border: none;
  background-color: #f0f0f0;
  box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.2), -4px -4px 10px rgba(255, 255, 255, 0.9);
}

.form-control:focus {
  outline: none;
  box-shadow: 6px 6px 15px rgba(0, 0, 0, 0.3), -6px -6px 15px rgba(255, 255, 255, 0.9);
}

</style>

<div style="text-align: right; margin-bottom: 20px;">
  <a href="{% url 'home' %}" class="btn btn-add">
    &laquo; Voltar
  </a>
</div>

{% for cadastro in cadastros %}
<div class="neuromorphic-card">
  <div class="card-body">
    <div style="display: flex; justify-content: space-between; align-items: center; ">
      <div>
        <h3 class="card-title">{{ cadastro.nome }}</h3>
      </div>
      <div class="icon-edit">
        <i class="fas fa-pen-to-square" data-bs-toggle="modal" data-bs-target="#editModal-{{ cadastro.Id }}"></i>
        <i class="fas fa-trash"  data-cadastro-id="{{ cadastro.Id }}"></i>
        <br>
        <br>
    </div>
  </div>
    <div class="card-info">
      <div class="info-row">
        {% if cadastro.cnpj !=  '' %}
        <span class="info-label">CNPJ:</span>
        <span class="info-value" style="margin-right: 8px;">{{ cadastro.cnpj }}</span>
        {% endif %}

        {% if cadastro.cpf %}
          <span class="info-label">CPF:</span>
          <span class="info-value">{{ cadastro.cpf }}</span>
        {% endif %}
      </div>
      {% if cadastro.ie %}
      <div class="info-row">
        <span class="info-label">IE:</span>
        <span class="info-value">{{ cadastro.ie }}</span>
      </div>
      {% endif %}

      {% if cadastro.telefone %}
      <div class="info-row">
        <span class="info-label">Telefone:</span>
        <span class="info-value">{{ cadastro.telefone }}</span>
      </div>
      {% endif %}
      {% if cadastro.celular %}
      <div class="info-row">
        <span class="info-label">Celular:</span>
        <span class="info-value">{{ cadastro.celular }}</span>
      </div>
      {% endif %}
      <div class="expand-toggle">
        <i class="fa-solid fa-angle-down icon-angle-down"></i>
      </div>
    </div>

    <div class="additional-info" style="display: none;">
      <div class="info-row">
        <span class="info-value">
          {% if cadastro.email %}
          <div class="mb-3">
            <strong>Email:</strong> {{ cadastro.email }}
          </div>
          {% endif %}
          {% if cadastro.endereco %}
          <div class="mb-3">
            <strong>Endereço:</strong> {{ cadastro.endereco }}
          </div>
          {% endif %}

          {% if cadastro.cidade %}
          <div class="mb-3">
            <strong>Cidade:</strong> {{ cadastro.cidade }}
          </div>
          {% endif %}

          {% if cadastro.bairro %}
          <div class="mb-3">
            <strong>Bairro:</strong> {{ cadastro.bairro }}
          </div>
          {% endif %}
          
          {% if cadastro.cep %}
          <div class="mb-3">
            <strong>CEP:</strong> {{ cadastro.cep }}
          </div>
          {% endif %}
        
          {% if cadastro.whatsapp %}
          <div class="mb-3">
            <strong>Whatsapp:</strong> {{ cadastro.whatsapp }}
          </div>
          {% endif %}

          {% for observacao in cadastro.observacoes_set.all %}
          {% if observacao.observacoes%}
          <strong >Observações:</strong>
          <div class="cadastro-list">
            <span>- {{ observacao.observacoes }}</span>
          </div>
          {% endif %}
          {% endfor %}
        </span>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editModal-{{ cadastro.Id }}" tabindex="-1" aria-labelledby="editModalLabel-{{ cadastro.Id }}" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel-{{ cadastro.Id }}">Editar Cadastro</h5>
        <button type="button" class="btn-close" style="font-size: large; margin-right: 10px;" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
    
        <form id="editForm-{{ cadastro.Id }}" method="post" action="{% url 'edit_cadastro' %}">
          {% csrf_token %}
      
          <input type="hidden" id="editId" name="editId" value="{{ cadastro.Id }}">

          <div class="mb-3">
            <label for="editNome" class="form-label">Nome:</label>
            <input type="text" class="form-control" id="editNome" name="editNome" value="{{ cadastro.nome }}">
          </div>
   
          <div class="mb-3">
            <label for="editCPF" class="form-label">CPF:</label>
            <input type="text" class="form-control" id="editCPF" name="editCPF" value="{{ cadastro.cpf }}">
          </div>

          <div class="mb-3">
            <label for="editCNPJ" class="form-label">CNPJ:</label>
            <input type="text" class="form-control" id="editCNPJ" name="editCNPJ" value="{{ cadastro.cnpj }}">
          </div>
          <div class="mb-3">
            <label for="editIE" class="form-label">IE:</label>
            <input type="text" class="form-control" id="editIE" name="editIE" value="{{ cadastro.ie }}">
          </div>
          <div class="mb-3">
            <label for="editEndereco" class="form-label">Endereço:</label>
            <input type="text" class="form-control" id="editEndereco" name="editEndereco" value="{{ cadastro.endereco }}">
          </div>
          <div class="mb-3">
            <label for="editIE" class="form-label">Cidade:</label>
            <input type="text" class="form-control" id="editCidade" name="editCidade" value="{{ cadastro.cidade }}">
          </div>
          <div class="mb-3">
            <label for="editBairro" class="form-label">Bairro:</label>
            <input type="text" class="form-control" id="editBairro" name="editBairro" value="{{ cadastro.bairro }}">
          </div>
          <div class="mb-3">
            <label for="editCEP" class="form-label">CEP:</label>
            <input type="text" class="form-control" id="editCEP" name="editCEP" value="{{ cadastro.cep }}">
          </div>
          <div class="mb-3">
            <label for="editTelefone" class="form-label">Telefone:</label>
            <input type="text" class="form-control" id="editTelefone" name="editTelefone" value="{{ cadastro.telefone }}">
          </div>
          <div class="mb-3">
            <label for="editCelular" class="form-label">Celular:</label>
            <input type="text" class="form-control" id="editCelular" name="editCelular" value="{{ cadastro.celular }}">
          </div>  
          <div class="mb-3">
            <label for="editCelular" class="form-label">WhatsApp:</label>
            <input type="text" class="form-control" id="editWhatsapp" name="editWhatsapp" value="{{ cadastro.whatsapp }}">
          </div>  

          <div class="mb-3">
            <label for="editEmail" class="form-label">Email:</label>
            <input type="text" class="form-control" id="editEmail" name="editEmail" value="{{ cadastro.email }}">
          </div>
          
          {% for observacao in cadastro.observacoes_set.all %}
          <div class="mb-3">
            <label for="editEmail" class="form-label">Observações:</label>
            <input type="text" class="form-control" id="editObservacoes" name="editObservacoes" value="{{ observacao.observacoes }}">
          </div>
          {% endfor %}
          <button type="submit" class="btn btn-add mt-3">
           
            <i class="fas fa-save"></i> Salvar
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}


{% if cadastros.paginator.num_pages > 1 %}
  <div class="pagination">
      <span class="step-links mb-5">
          {% if cadastros.has_previous %}
              <a href="?page=1">&laquo; Primeira</a>
              <a href="?page={{ cadastros.previous_page_number }}">Anterior</a>
          {% endif %}

          <span class="current">
              Página {{ cadastros.number }} de {{ cadastros.paginator.num_pages }}.
          </span>

          {% if cadastros.has_next %}
              <a href="?page={{ cadastros.next_page_number }}">Próxima</a>
              <a href="?page={{ cadastros.paginator.num_pages }}">Última &raquo;</a>
          {% endif %}
      </span>
  </div>
{% endif %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  $(document).ready(function() {
    $('.expand-toggle').on('click', function() {
      $(this).closest('.card-body').find('.additional-info').slideToggle(200);
      $(this).find('.icon-angle-down').toggleClass('icon-rotate'); 
    });
  });
</script>


<script>
  $(document).ready(function() {
    $('.fa-trash').on('click', function() {
        const cadastroId = $(this).data('cadastro-id');
        if (confirm('Tem certeza de que deseja excluir este cadastro?')) {
            $.ajax({
                type: 'POST',
                url: '/excluir-cadastro/',  // Substitua pela URL correta da sua view de exclusão
                data: {
                    cadastro_id: cadastroId,
                    csrfmiddlewaretoken: '{{ csrf_token }}'  // Adicione o token CSRF
                },
                success: function(response) {
                    window.location.reload();
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }
    });
});
</script>

agenda/main/templates/screens/lista.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lista de cadastros</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <style>
        html,
        body {
            background-color: rgb(244, 244, 244);
            height: 100%;
            margin: 0;
            font: normal 80% Arial, Helvetica, sans-serif;
        }

        .content {
            margin-top: 30px;
            position: relative;
            width: 100%;
            z-index: 1;
        }
    </style>
</head>

<body>
    <br>

    <div class="container content">
        {% include 'components/listar_cadastro.html' %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>